name: Generate Snake Contribution Grid  
on:  
  schedule:  
    - cron: "0 0 * * *"  # Runs daily at midnight  

jobs:  
  build:  
    runs-on: ubuntu-latest  
    steps:  
      - uses: Platane/snk@v2  
        with:  
          github_user_name: akki9392  
          outputs: github-contribution-grid-snake.svg  
      - uses: crazy-max/ghaction-github-pages@v3  
        with:  
          target_branch: output  
          build_dir: .  
        env:  
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
